### ISSUE TITLE
Symfony App inside the app folder is not being deployed to Github

### ISSUE THREAD

**Issue by ziegfridhn** [yemiwebby/symfony-docker-tut#1]
Hi,

I followed this step in make my API app and when I'm trying to upload this to github the app folder is not being add nor commited to my git. I'm using Linux Mint as my OS. I have attached screenshots below

![image](https://user-images.githubusercontent.com/85665550/122712622-c95a5580-d296-11eb-8934-19cc49471aa5.png)

Here is a screenshot of my file system

![image](https://user-images.githubusercontent.com/85665550/122712738-fc9ce480-d296-11eb-8306-46d0f0500ef6.png)

**Comment by yemiwebby** [comment]
Sorry about that @ziegfridhn. This is obviously not an issue with the steps in the tutorial. I will suggest that you re-initialize Git within the root directory for this project on your local system again.

Navigate to the root folder and :
```bash
rm -rf .git
```

```bash
git init
git add .
git commit -m "Initial commit"
```

And so on. I hope that helps?

**Comment by ziegfridhn** [comment]
I tried that. But unfortunately, that didn't work.

**Comment by ziegfridhn** [comment]
The fix for my issue is to make sure all folder is not a git repository. In my case (since it's a pre-existing project) .git folder should be removed inside the `app/` folder and re-initialized git on the root directory.
